# Production
SUPABASE_URL = "https://awsknfddhqnqznxrdhwu.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3c2tuZmRkaHFucXpueHJkaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTU1NzUsImV4cCI6MjA2ODMzMTU3NX0.5JoPHMJPk230kJPdRZDPf_a8tI6evG8nLgLWdidGUSI"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3c2tuZmRkaHFucXpueHJkaHd1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mjc1NTU3NSwiZXhwIjoyMDY4MzMxNTc1fQ.LRIUDiWKcL61DCk-UVpw8-5EyNk2bqGka3HDECI-hxA"
